<p><head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<link rel="stylesheet" type="text/css" href="bc.css">
<!--
<script src="run_prettify.js" type="text/javascript"></script>
<script src="https://google-code-prettify.googlecode.com/svn/loader/run_prettify.js" type="text/javascript"></script>
-->
<script src="https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js" type="text/javascript"></script>
</head></p>
<!---

- implemented NewFamilySymbolProfile sample app
  https://github.com/jeremytammik/NewFamilySymbolProfile
  13871503 [Sweep Profile From Family]
  https://forums.autodesk.com/t5/revit-api-forum/sweep-profile-from-family/m-p/7751112
  https://forums.autodesk.com/t5/revit-api-forum/sweep-using-profile-family/m-p/6057115

NewFamilySymbolProfile sample #RevitAPI add-in @AutodeskRevit #bim #dynamobim @AutodeskForge #ForgeDevCon http://bit.ly/newfamilysymbolprofile

Questions on how to use <code>NewFamilySymbolProfile</code> have come up a couple of times in the Revit API discussion forum.
The short answer is: retrieve the family symbol from the profile family, then call the creation application <code>NewFamilySymbolProfile</code> method.
I implemented a new sample add-in for you to demonstrate the steps using the <i>Profiles_L-Angles.rfa</i> profile family...

--->

<h3>NewFamilySymbolProfile Sample Add-In</h3>
<p>I've been answering rather a lot of queries in
the <a href="http://forums.autodesk.com/t5/revit-api-forum/bd-p/160">Revit API discussion forum</a> lately,
leading me to once again become <a href="#2">top solution author</a>; here is one of the latest:</p>
<h4><a name="1"></a>How to use NewFamilySymbolProfile</h4>
<p>Questions on how to use <code>NewFamilySymbolProfile</code> have come up a couple of times, e.g., in the following threads:</p>
<ul>
<li><a href="https://forums.autodesk.com/t5/revit-api-forum/load-profile-for-newsweep-command/td-p/5117864">Load profile for <code>NewSweep</code> command</a></li>
<li><a href="https://forums.autodesk.com/t5/revit-api-forum/sweep-using-profile-family/m-p/6057115">Sweep using profile family</a></li>
<li><a href="https://forums.autodesk.com/t5/revit-api-forum/sweep-profile-from-family/m-p/7751112">Sweep profile from family</a></li>
</ul>
<p>In the second, Revitalizer provides a succinct answer, saying:</p>
<blockquote>
<p>The next step after retrieving the family symbol from the profile family is to call
the <a href="http://www.revitapidocs.com/2018.1/0fd22223-8ca8-2955-e2ee-7d83d853ee8f.htm"><code>Autodesk.Revit.Creation.Application</code> <code>NewFamilySymbolProfile</code> method</a>:</p>
</blockquote>
<pre class="code">
  FamilySymbolProfile
    Application.NewFamilySymbolProfile(
      FamilySymbol familySymbol )
</pre>

<p>However, the first two thread answers were insufficiently complete and clear, hence the third follow-up thread.</p>
<p><strong>Question:</strong> I want to pass a profile from an existing profile family to <code>FamilyCreate.NewSweep</code>.</p>
<p>I looked at the thread
on <a href="https://forums.autodesk.com/t5/revit-api-forum/load-profile-for-newsweep-command/td-p/5117864">loading a profile for the <code>NewSweep</code> command</a>.</p>
<p>Jeremy's comments from this post indicate that the profile family cannot be passed directly, but that the profile geometry needs to be recreated. Am I reading this correctly?</p>
<p>You can certainly retrieve a profile for a sweep operation from a family file.</p>
<p>However, the family file does not provide any provision for storing a profile per se, so you will have to make use of the other geometrical options available in that context to define some kind of geometry specifying the sweep profile.</p>
<p>You can then parse that geometry, extract the profile information, and put together the required curve array in your add-in.</p>
<p>As mentioned in some other Sweep posts, there are many samples that create a new profile, but none that accept a <code>FamilySymbolProfile</code> directly.</p>
<p>Can this be done?</p>
<p><strong>Answer:</strong> This question was actually answered in the thread
on <a href="https://forums.autodesk.com/t5/revit-api-forum/sweep-using-profile-family/m-p/6057115">sweep using profile family</a>.</p>
<p>One first needs to create a <code>FamilySymbolProfile</code> object from the <code>FamilySymbol</code> generated by loading the profile Family, then use the  <code>FamilyFactory.NewSweep</code> method passing in the <code>FamilySymbolProfile</code> as <code>SweepProfile</code>.</p>
<p>I implemented a new sample
add-in <a href="https://github.com/jeremytammik/NewFamilySymbolProfile">NewFamilySymbolProfile</a> for
you to demonstrate the steps using the <em>Profiles_L-Angles.rfa</em> profile family.</p>
<ul>
<li>C:/Users/All Users/Autodesk/RVT 2018/Libraries/UK/Profiles/Framing/Steel/Profiles_L-Angles.rfa</li>
</ul>
<p><center>
<img src="img/l_angle_rfa.png" alt="UK Profiles Framing Steel Profiles_L-Angles.rfa" width="177"/>
</center></p>
<p>Here is the code:</p>
<pre class="code">
<span style="color:blue;">#region</span>&nbsp;Namespaces
<span style="color:blue;">using</span>&nbsp;System.Collections.Generic;
<span style="color:blue;">using</span>&nbsp;System.Diagnostics;
<span style="color:blue;">using</span>&nbsp;Autodesk.Revit.ApplicationServices;
<span style="color:blue;">using</span>&nbsp;Autodesk.Revit.Attributes;
<span style="color:blue;">using</span>&nbsp;Autodesk.Revit.DB;
<span style="color:blue;">using</span>&nbsp;Autodesk.Revit.UI;
<span style="color:blue;">#endregion</span>

<span style="color:blue;">namespace</span>&nbsp;NewFamilySymbolProfile
{
&nbsp;&nbsp;[<span style="color:#2b91af;">Transaction</span>(&nbsp;<span style="color:#2b91af;">TransactionMode</span>.Manual&nbsp;)]
&nbsp;&nbsp;<span style="color:blue;">public</span>&nbsp;<span style="color:blue;">class</span>&nbsp;<span style="color:#2b91af;">Command</span>&nbsp;:&nbsp;<span style="color:#2b91af;">IExternalCommand</span>
&nbsp;&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:blue;">const</span>&nbsp;<span style="color:blue;">string</span>&nbsp;_filepath&nbsp;=&nbsp;<span style="color:#a31515;">&quot;C:/Users/All&nbsp;Users/Autodesk&quot;</span>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;+&nbsp;<span style="color:#a31515;">&quot;/RVT&nbsp;2018/Libraries/UK/Profiles/Framing/Steel&quot;</span>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;+&nbsp;<span style="color:#a31515;">&quot;/Profiles_L-Angles.rfa&quot;</span>;

&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:blue;">public</span>&nbsp;<span style="color:#2b91af;">Result</span>&nbsp;Execute(
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#2b91af;">ExternalCommandData</span>&nbsp;commandData,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:blue;">ref</span>&nbsp;<span style="color:blue;">string</span>&nbsp;message,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#2b91af;">ElementSet</span>&nbsp;elements&nbsp;)
&nbsp;&nbsp;&nbsp;&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#2b91af;">UIApplication</span>&nbsp;uiapp&nbsp;=&nbsp;commandData.Application;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#2b91af;">UIDocument</span>&nbsp;uidoc&nbsp;=&nbsp;uiapp.ActiveUIDocument;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#2b91af;">Application</span>&nbsp;app&nbsp;=&nbsp;uiapp.Application;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#2b91af;">Document</span>&nbsp;doc&nbsp;=&nbsp;uidoc.Document;

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#2b91af;">Document</span>&nbsp;profile_doc&nbsp;=&nbsp;app.OpenDocumentFile(&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_filepath&nbsp;);

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:green;">//&nbsp;The&nbsp;profile&nbsp;document&nbsp;contains&nbsp;no&nbsp;family&nbsp;sybols:</span>

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#2b91af;">FilteredElementCollector</span>&nbsp;symbols
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=&nbsp;<span style="color:blue;">new</span>&nbsp;<span style="color:#2b91af;">FilteredElementCollector</span>(&nbsp;profile_doc&nbsp;)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.OfClass(&nbsp;<span style="color:blue;">typeof</span>(&nbsp;<span style="color:#2b91af;">FamilySymbol</span>&nbsp;)&nbsp;);

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#2b91af;">Debug</span>.Assert(&nbsp;0&nbsp;==&nbsp;symbols.GetElementCount(),&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#a31515;">&quot;expected&nbsp;no&nbsp;family&nbsp;symbol&quot;</span>&nbsp;);

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:green;">//&nbsp;Load&nbsp;the&nbsp;profile&nbsp;family&nbsp;to&nbsp;generate&nbsp;them:</span>

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#2b91af;">FamilySymbol</span>&nbsp;profile_symbol&nbsp;=&nbsp;<span style="color:blue;">null</span>;

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:blue;">using</span>(&nbsp;<span style="color:#2b91af;">Transaction</span>&nbsp;tx&nbsp;=&nbsp;<span style="color:blue;">new</span>&nbsp;<span style="color:#2b91af;">Transaction</span>(&nbsp;doc&nbsp;)&nbsp;)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tx.Start(&nbsp;<span style="color:#a31515;">&quot;Load&nbsp;Profile&nbsp;Family&quot;</span>&nbsp;);

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#2b91af;">Family</span>&nbsp;family;

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;doc.LoadFamily(&nbsp;_filepath,&nbsp;<span style="color:blue;">out</span>&nbsp;family&nbsp;);

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tx.Commit();

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#2b91af;">ISet</span>&lt;<span style="color:#2b91af;">ElementId</span>&gt;&nbsp;ids&nbsp;=&nbsp;family.GetFamilySymbolIds();

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:blue;">foreach</span>(&nbsp;<span style="color:#2b91af;">ElementId</span>&nbsp;id&nbsp;<span style="color:blue;">in</span>&nbsp;ids&nbsp;)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;profile_symbol&nbsp;=&nbsp;doc.GetElement(&nbsp;id&nbsp;)&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:blue;">as</span>&nbsp;<span style="color:#2b91af;">FamilySymbol</span>;

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#2b91af;">Debug</span>.Print(&nbsp;profile_symbol.Name&nbsp;);
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:green;">//&nbsp;Generate&nbsp;the&nbsp;family&nbsp;symbol&nbsp;profile:</span>

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#2b91af;">FamilySymbolProfile</span>&nbsp;fsp&nbsp;=&nbsp;<span style="color:blue;">null</span>;

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:blue;">if</span>(&nbsp;<span style="color:blue;">null</span>&nbsp;!=&nbsp;profile_symbol&nbsp;)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:blue;">using</span>(&nbsp;<span style="color:#2b91af;">Transaction</span>&nbsp;tx&nbsp;=&nbsp;<span style="color:blue;">new</span>&nbsp;<span style="color:#2b91af;">Transaction</span>(&nbsp;doc&nbsp;)&nbsp;)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tx.Start(&nbsp;<span style="color:#a31515;">&quot;Create&nbsp;FamilySymbolProfile&quot;</span>&nbsp;);
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;fsp&nbsp;=&nbsp;app.Create.NewFamilySymbolProfile(&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;profile_symbol&nbsp;);
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tx.Commit();
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:blue;">return</span>&nbsp;<span style="color:#2b91af;">Result</span>.Succeeded;
&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;}
}
</pre>

<p>The comments explain all the important steps.</p>
<h4><a name="2"></a>Top Solution Author</h4>
<p>As said, I have been answering rather a lot of queries lately, leading to a new top solution author record score of 37, afaik:</p>
<p><center>
<img src="img/2018-02-08_top_solution_author_37.png" alt="Top solution author" width="231"/>
</center></p>