<p><head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<link rel="stylesheet" type="text/css" href="bc.css"></p>
<script src="https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js" type="text/javascript"></script>
<p></head></p>
<!---

- https://autodesk.slack.com/archives/C0SR6NAP8/p1651517777022079

- Forge Data Days Global Event
  https://forge.autodesk.com/blog/announcing-forge-data-days-global-event-series

- https://forums.autodesk.com/t5/revit-api-forum/get-curves-of-slab-was-joined/td-p/11140489
  get curves of slab was joined
  to obtain separate corve loops for separate element parts generated by joining it with another element

twitter:

Forge Data Days, the updated Revit 2023 developer's guide and a nice JoinGeometryUtils sample to obtain closed loops for joined element parts in the #RevitAPI @AutodeskForge @AutodeskRevit #bim #DynamoBim #ForgeDevCon https://autode.sk/joingeometryutils

Finally a chance to meet and learn live about Forge, the updated developer's guide and a nice <code>JoinGeometryUtils</code> sample
&ndash; Revit 2023 developer's guide
&ndash; Forge Data Days
&ndash; Obtaining closed loops for joined element parts
&ndash; Create and style your QR code
&ndash; La Serre greenhouse wheelbarrow ballet...

linkedin:

Forge Data Days, the updated Revit 2023 developer's guide and a nice JoinGeometryUtils sample to obtain closed loops for joined element parts in the #RevitAPI

https://autode.sk/joingeometryutils

Finally a chance to meet and learn live about Forge!

- Revit 2023 developer's guide
- Forge Data Days
- Obtaining closed loops for joined element parts
- Create and style your QR code
- La Serre greenhouse wheelbarrow ballet...

#bim #DynamoBim #ForgeDevCon #Revit #API #IFC #SDK #AI #VisualStudio #Autodesk #AEC #adsk

the [Revit API discussion forum](http://forums.autodesk.com/t5/revit-api-forum/bd-p/160) thread

<center>
<img src="img/" alt="" title="" width="600"/>
<p style="font-size: 80%; font-style:italic"></p>
</center>

-->

<h3>Forge Data Days and JoinGeometryUtils</h3>
<p>Finally a chance to meet and learn live about Forge, the updated developer's guide and a nice <code>JoinGeometryUtils</code> sample:</p>
<ul>
<li><a href="#2">Revit 2023 developer's guide</a></li>
<li><a href="#3">Forge Data Days</a></li>
<li><a href="#4">Obtaining closed loops for joined element parts</a></li>
<li><a href="#5">Create and style your QR code</a></li>
<li><a href="#6">La Serre &ndash; greenhouse wheelbarrow ballet</a></li>
</ul>
<h4><a name="2"></a> Revit 2023 Developer's Guide</h4>
<p>The <a href="https://help.autodesk.com/view/RVT/2023/ENU/?guid=Revit_API_Revit_API_Developers_Guide_html">English version of the Revit 2023 Developer's Guide</a> is
now online.</p>
<p>The development team is still actively working on an issue with the Japanese text.</p>
<h4><a name="3"></a> Forge Data Days</h4>
<p>Finally, after the world-wide pandemic break, which also affected our traditional yearly DevDays, we can meet again live, face to face:</p>
<p>The Forge Data Days are coming up soon, a one-day, in-person event happening in 20 cities worldwide, to learn how to fully unlock the value of your data with Forge.
There are a limited number of seats available for each event, so I encourage you to register as soon as possible once you have decided that this is of interest for you.</p>
<p>At Forge Data Days, you’ll hear directly from experts on how Forge is powering enterprise digital transformation.
See how we are making data more granular, standardized, and transparent.
This can help you connect your teams, processes, and workflows.
Learn how new Forge data capabilities and APIs can increase your productivity, automation, and profitability. </p>
<p>With the following exclusive Early Bird registration links for the first five locations, you can choose between different dates and European cities to join us at:</p>
<ul>
<li>May 31st &ndash; <a href="https://cvent.autodesk.com/event/c064e191-cced-4cf6-a0ff-56a92a3c2689/summary">Munich, Germany</a></li>
<li>June 2nd &ndash; <a href="https://cvent.autodesk.com/event/994e1f82-52fc-41a2-9a64-efadde9e4273/summary">Gothenburg, Sweden</a></li>
<li>June 7th &ndash; <a href="https://cvent.autodesk.com/event/bedd310d-fa7d-4b02-99dd-2c4c5b40293d/summary">Birmingham, UK</a></li>
<li>June 9th &ndash; <a href="https://cvent.autodesk.com/event/5733cfc3-51cf-41fb-bacf-457ba6b1ae97/summary">Milan, Italy</a></li>
<li>June 14th &ndash; <a href="https://cvent.autodesk.com/event/84021b3b-9286-4586-af2a-c6b1f2b5f301/summary">Barcelona, Spain</a></li>
<li><a href="https://forge.autodesk.com/forge-data-days">All event locations</a></li>
</ul>
<p>Personally, I will probably be joining the event in Barcelona.</p>
<p>Registration opens to the public today, May 3rd, and spots will fill up fast, so don't wait too long making up your mind...</p>
<p>To learn more about the event, please check out
the <a href="https://forge.autodesk.com/blog/announcing-forge-data-days-global-event-series">Forge Data Days global event series announcement</a> and 
the <a href="https://forge.autodesk.com/forge-data-days">Forge Data Days event page</a>.</p>
<p><center>
<img src="img/2022_forge_data_days.png" alt="Forge Data Days" title="Forge Data Days" width="800"/> <!-- 1200 -->
</center></p>
<h4><a name="4"></a> Obtaining Closed Loops for Joined Element Parts</h4>
<p>Returning to the Revit API,
Richard <a href="https://forums.autodesk.com/t5/user/viewprofilepage/user-id/1035859">RPThomas108</a> Thomas shared another of his brilliant solutions and adds a new entry to the list of
the <a href="https://thebuildingcoder.typepad.com/blog/about-the-author.html#5.52">often overlooked Revit API Util</a> in 
the <a href="http://forums.autodesk.com/t5/revit-api-forum/bd-p/160">Revit API discussion forum</a> thread
on how to <a href="https://forums.autodesk.com/t5/revit-api-forum/get-curves-of-slab-was-joined/td-p/11140489">get curves of a joined slab</a>,
to obtain separate curve loops for the separate parts of an element that are generated by joining it with another element:</p>
<p><strong>Question:</strong> I have a slab that is joined with a beam.
How can I get two contiguous curves as highlighted in this picture?</p>
<p><center>
<img src="img/slab_joined_loops_1.png" alt="Slab joined loops" title="Slab joined loops" width="600"/> <!-- 1206 -->
</center></p>
<p><strong>Answer:</strong> The easiest way to obtain the loops for that is to reverse the join order within a transaction that is rolled back so that the beam cuts the slab.
Currently, with slab cutting beam, you will get a single edge loop for the slab top face with extra 'contextual' edges where the edge is hidden by the joins.</p>
<p>The below code uses the following <code>JoinGeometryUtils</code> API calls to achieve what you need:</p>
<ul>
<li>GetJoinedElements</li>
<li>IsCuttingElementInJoin</li>
<li>SwitchJoinOrder</li>
</ul>
<p><center>
<img src="img/slab_joined_loops_2.png" alt="Slab joined loops" title="Slab joined loops" width="600"/> <!-- 1034 -->
</center></p>
<pre class="code">
&nbsp;&nbsp;Public</span>&nbsp;<span style="color:blue;">Function</span>&nbsp;<span style="color:#74531f;">Obj_220503a</span>(<span style="color:#1f377f;">commandData</span>&nbsp;<span style="color:blue;">As</span>&nbsp;ExternalCommandData,&nbsp;<span style="color:blue;">ByRef</span>&nbsp;<span style="color:#1f377f;">message</span>&nbsp;<span style="color:blue;">As</span>&nbsp;<span style="color:blue;">String</span>,&nbsp;<span style="color:#1f377f;">elements</span>&nbsp;<span style="color:blue;">As</span>&nbsp;ElementSet)&nbsp;<span style="color:blue;">As</span>&nbsp;Result
&nbsp;&nbsp;<span style="color:blue;">Dim</span>&nbsp;<span style="color:#1f377f;">IntUIApp</span>&nbsp;<span style="color:blue;">As</span>&nbsp;UIApplication&nbsp;=&nbsp;commandData.Application
&nbsp;&nbsp;<span style="color:blue;">Dim</span>&nbsp;<span style="color:#1f377f;">IntUIDoc</span>&nbsp;<span style="color:blue;">As</span>&nbsp;UIDocument&nbsp;=&nbsp;commandData.Application.ActiveUIDocument
&nbsp;&nbsp;<span style="color:blue;">Dim</span>&nbsp;<span style="color:#1f377f;">IntDoc</span>&nbsp;<span style="color:blue;">As</span>&nbsp;Document&nbsp;=&nbsp;IntUIDoc.Document

&nbsp;&nbsp;<span style="color:blue;">Dim</span>&nbsp;<span style="color:#1f377f;">FEC_Flr</span>&nbsp;<span style="color:blue;">As</span>&nbsp;<span style="color:blue;">New</span>&nbsp;FilteredElementCollector(IntDoc,&nbsp;IntDoc.ActiveView.Id)
&nbsp;&nbsp;<span style="color:blue;">Dim</span>&nbsp;<span style="color:#1f377f;">ECF_Flr</span>&nbsp;<span style="color:blue;">As</span>&nbsp;<span style="color:blue;">New</span>&nbsp;ElementClassFilter(<span style="color:blue;">GetType</span>(Floor))

&nbsp;&nbsp;<span style="color:blue;">Dim</span>&nbsp;<span style="color:#1f377f;">Els</span>&nbsp;<span style="color:blue;">As</span>&nbsp;List(<span style="color:blue;">Of</span>&nbsp;Element)&nbsp;=&nbsp;FEC_Flr.WherePasses(ECF_Flr).ToElements
&nbsp;&nbsp;<span style="color:blue;">Dim</span>&nbsp;<span style="color:#1f377f;">Curves</span>&nbsp;<span style="color:blue;">As</span>&nbsp;<span style="color:blue;">New</span>&nbsp;List(<span style="color:blue;">Of</span>&nbsp;Tuple(<span style="color:blue;">Of</span>&nbsp;List(<span style="color:blue;">Of</span>&nbsp;Curve),&nbsp;Plane))

&nbsp;&nbsp;<span style="color:blue;">Using</span>&nbsp;Tx&nbsp;<span style="color:blue;">As</span>&nbsp;<span style="color:blue;">New</span>&nbsp;Transaction(IntDoc,&nbsp;<span style="color:#a31515;">&quot;Gather&quot;</span>)
&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#8f08c4;">If</span>&nbsp;Tx.Start&nbsp;=&nbsp;TransactionStatus.Started&nbsp;<span style="color:#8f08c4;">Then</span>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#8f08c4;">For</span>&nbsp;i&nbsp;=&nbsp;0&nbsp;<span style="color:#8f08c4;">To</span>&nbsp;Els.Count&nbsp;-&nbsp;1
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:blue;">Dim</span>&nbsp;<span style="color:#1f377f;">El</span>&nbsp;<span style="color:blue;">As</span>&nbsp;Element&nbsp;=&nbsp;Els(i)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:blue;">Dim</span>&nbsp;<span style="color:#1f377f;">Ids</span>&nbsp;<span style="color:blue;">As</span>&nbsp;List(<span style="color:blue;">Of</span>&nbsp;ElementId)&nbsp;=&nbsp;JoinGeometryUtils.GetJoinedElements(IntDoc,&nbsp;El)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:blue;">Dim</span>&nbsp;<span style="color:#1f377f;">FEC_Fra</span>&nbsp;<span style="color:blue;">As</span>&nbsp;<span style="color:blue;">New</span>&nbsp;FilteredElementCollector(IntDoc,&nbsp;Ids)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:blue;">Dim</span>&nbsp;<span style="color:#1f377f;">ECF_Fra</span>&nbsp;<span style="color:blue;">As</span>&nbsp;<span style="color:blue;">New</span>&nbsp;ElementCategoryFilter(BuiltInCategory.OST_StructuralFraming)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:blue;">Dim</span>&nbsp;<span style="color:#1f377f;">Els0</span>&nbsp;<span style="color:blue;">As</span>&nbsp;List(<span style="color:blue;">Of</span>&nbsp;Element)&nbsp;=&nbsp;FEC_Fra.WherePasses(ECF_Fra).ToElements

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#8f08c4;">For</span>&nbsp;i0&nbsp;=&nbsp;0&nbsp;<span style="color:#8f08c4;">To</span>&nbsp;Els0.Count&nbsp;-&nbsp;1
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#8f08c4;">If</span>&nbsp;JoinGeometryUtils.IsCuttingElementInJoin(IntDoc,&nbsp;El,&nbsp;Els0(i0))&nbsp;<span style="color:#8f08c4;">Then</span>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;JoinGeometryUtils.SwitchJoinOrder(IntDoc,&nbsp;El,&nbsp;Els0(i0))
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#8f08c4;">End</span>&nbsp;<span style="color:#8f08c4;">If</span>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#8f08c4;">Next</span>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;IntDoc.Regenerate()

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:blue;">Dim</span>&nbsp;<span style="color:#1f377f;">geomEl</span>&nbsp;<span style="color:blue;">As</span>&nbsp;GeometryElement&nbsp;=&nbsp;El.Geometry(<span style="color:blue;">New</span>&nbsp;Options&nbsp;<span style="color:blue;">With</span>&nbsp;{.DetailLevel&nbsp;=&nbsp;ViewDetailLevel.Fine})
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#8f08c4;">For</span>&nbsp;<span style="color:#8f08c4;">Each</span>&nbsp;ob&nbsp;<span style="color:blue;">As</span>&nbsp;GeometryObject&nbsp;<span style="color:#8f08c4;">In</span>&nbsp;geomEl
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#8f08c4;">If</span>&nbsp;<span style="color:blue;">GetType</span>(Solid)&nbsp;<span style="color:blue;">Is</span>&nbsp;ob.GetType&nbsp;<span style="color:#8f08c4;">Then</span>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:blue;">Dim</span>&nbsp;<span style="color:#1f377f;">S</span>&nbsp;<span style="color:blue;">As</span>&nbsp;Solid&nbsp;=&nbsp;ob

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#8f08c4;">For</span>&nbsp;ix&nbsp;=&nbsp;0&nbsp;<span style="color:#8f08c4;">To</span>&nbsp;S.Faces.Size&nbsp;-&nbsp;1
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:blue;">Dim</span>&nbsp;<span style="color:#1f377f;">PF</span>&nbsp;<span style="color:blue;">As</span>&nbsp;PlanarFace&nbsp;=&nbsp;<span style="color:blue;">TryCast</span>(S.Faces.Item(ix),&nbsp;PlanarFace)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#8f08c4;">If</span>&nbsp;PF&nbsp;<span style="color:blue;">Is</span>&nbsp;<span style="color:blue;">Nothing</span>&nbsp;<span style="color:#8f08c4;">Then</span>&nbsp;<span style="color:#8f08c4;">Continue</span>&nbsp;<span style="color:#8f08c4;">For</span>&nbsp;<span style="color:blue;">Else</span>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#8f08c4;">If</span>&nbsp;PF.FaceNormal.IsAlmostEqualTo(XYZ.BasisZ)&nbsp;<span style="color:#8f08c4;">Then</span>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:blue;">Dim</span>&nbsp;<span style="color:#1f377f;">CrvSet</span>&nbsp;<span style="color:blue;">As</span>&nbsp;<span style="color:blue;">New</span>&nbsp;List(<span style="color:blue;">Of</span>&nbsp;Curve)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:blue;">Dim</span>&nbsp;<span style="color:#1f377f;">CLL</span>&nbsp;<span style="color:blue;">As</span>&nbsp;List(<span style="color:blue;">Of</span>&nbsp;CurveLoop)&nbsp;=&nbsp;PF.GetEdgesAsCurveLoops
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#8f08c4;">For</span>&nbsp;<span style="color:#8f08c4;">Each</span>&nbsp;CL&nbsp;<span style="color:blue;">As</span>&nbsp;CurveLoop&nbsp;<span style="color:#8f08c4;">In</span>&nbsp;CLL
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#8f08c4;">For</span>&nbsp;<span style="color:#8f08c4;">Each</span>&nbsp;C&nbsp;<span style="color:blue;">As</span>&nbsp;Curve&nbsp;<span style="color:#8f08c4;">In</span>&nbsp;CL
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CrvSet.Add(C)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#8f08c4;">Next</span>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#8f08c4;">Next</span>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Curves.Add(<span style="color:blue;">New</span>&nbsp;Tuple(<span style="color:blue;">Of</span>&nbsp;List(<span style="color:blue;">Of</span>&nbsp;Curve),&nbsp;Plane)(CrvSet,&nbsp;PF.GetSurface))
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#8f08c4;">End</span>&nbsp;<span style="color:#8f08c4;">If</span>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#8f08c4;">Next</span>

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#8f08c4;">End</span>&nbsp;<span style="color:#8f08c4;">If</span>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#8f08c4;">Next</span>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#8f08c4;">Next</span>

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Tx.RollBack()
&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#8f08c4;">End</span>&nbsp;<span style="color:#8f08c4;">If</span>
&nbsp;&nbsp;<span style="color:blue;">End</span>&nbsp;<span style="color:blue;">Using</span>
&nbsp;&nbsp;<span style="color:blue;">Using</span>&nbsp;Tx&nbsp;<span style="color:blue;">As</span>&nbsp;<span style="color:blue;">New</span>&nbsp;Transaction(IntDoc,&nbsp;<span style="color:#a31515;">&quot;Draw&quot;</span>)
&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#8f08c4;">If</span>&nbsp;Tx.Start&nbsp;=&nbsp;TransactionStatus.Started&nbsp;<span style="color:#8f08c4;">Then</span>

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#8f08c4;">For</span>&nbsp;<span style="color:#8f08c4;">Each</span>&nbsp;item&nbsp;<span style="color:blue;">As</span>&nbsp;Tuple(<span style="color:blue;">Of</span>&nbsp;List(<span style="color:blue;">Of</span>&nbsp;Curve),&nbsp;Plane)&nbsp;<span style="color:#8f08c4;">In</span>&nbsp;Curves
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:blue;">Dim</span>&nbsp;<span style="color:#1f377f;">PL</span>&nbsp;<span style="color:blue;">As</span>&nbsp;Plane&nbsp;=&nbsp;item.Item2
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:blue;">Dim</span>&nbsp;<span style="color:#1f377f;">SKP</span>&nbsp;<span style="color:blue;">As</span>&nbsp;SketchPlane&nbsp;=&nbsp;SketchPlane.Create(IntDoc,&nbsp;PL)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#8f08c4;">For</span>&nbsp;<span style="color:#8f08c4;">Each</span>&nbsp;C&nbsp;<span style="color:blue;">As</span>&nbsp;Curve&nbsp;<span style="color:#8f08c4;">In</span>&nbsp;item.Item1
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;IntDoc.Create.NewModelCurve(C,&nbsp;SKP)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#8f08c4;">Next</span>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#8f08c4;">Next</span>

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Tx.Commit()
&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#8f08c4;">End</span>&nbsp;<span style="color:#8f08c4;">If</span>
&nbsp;&nbsp;<span style="color:blue;">End</span>&nbsp;<span style="color:blue;">Using</span>

&nbsp;&nbsp;<span style="color:#8f08c4;">Return</span>&nbsp;Result.Succeeded
<span style="color:blue;">End</span>&nbsp;<span style="color:blue;">Function</span>
</pre>

<h4><a name="5"></a> Create and Style Your QR Code</h4>
<p>Moving away from programming topics, I was not aware how much freedom you can have in styling a QR code until I took a look at
the <a href="https://www.qrcode-monkey.com">qrcode-monkey</a>.</p>
<h4><a name="6"></a> La Serre &ndash; Greenhouse Wheelbarrow Ballet</h4>
<p>Finally, unrelated to Revit and other hi-tech, just for fun, if you feel like a five-minute humorous poetic break, take a look at
<a href="https://youtu.be/G1XarNWgzCk">La Serre</a> by Didier André and Jean-Paul Lefeuvre,
a banjo-accompanied circus artist greenhouse wheelbarrow ballet:</p>
<iframe width="480" height="270" src="https://www.youtube.com/embed/G1XarNWgzCk" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

<blockquote>
<p>Formés au Centre national des arts du cirque, Jean-Paul Lefeuvre et Didier André ... ces deux circassiens ont étayé leur univers jusqu'à créer en 2001 <i>La Serre</i>, spectacle poético-agricole ... Dans un univers ingénieux, ces "Buster Keaton" de l'horticulture parsèment d'humour absurde et de rêverie aérienne leur grande humanité.</p>
<p><i>Trained at the national centre of circus art, Jean-Paul Lefeuvre and Didier André ... created La Serre in 2001, a poetic-agricultural show ... in an ingenious universe, these "Buster Keatons" of horticulture sprinkle their great humanity with absurd humour and aerial reverie.</i></p>
</blockquote>