<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<link rel="stylesheet" type="text/css" href="bc.css">
<script src="https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js" type="text/javascript"></script>
</head>

<!---

- https://autodesk.slack.com/archives/C0SR6NAP8/p1651517777022079

- Forge Data Days Global Event
  https://forge.autodesk.com/blog/announcing-forge-data-days-global-event-series

- https://forums.autodesk.com/t5/revit-api-forum/get-curves-of-slab-was-joined/td-p/11140489
  get curves of slab was joined
  to obtain separate corve loops for separate element parts generated by joining it with another element
  
twitter:

 #RevitAPI code @AutodeskForge @AutodeskRevit #bim #DynamoBim #ForgeDevCon 

&ndash; 
...

linkedin:

#bim #DynamoBim #ForgeDevCon #Revit #API #IFC #SDK #AI #VisualStudio #Autodesk #AEC #adsk

the [Revit API discussion forum](http://forums.autodesk.com/t5/revit-api-forum/bd-p/160) thread

<center>
<img src="img/" alt="" title="" width="600"/>
<p style="font-size: 80%; font-style:italic"></p>
</center>

-->

### Forge Data Days



####<a name="2"></a> Revit 2023 Developer's Guide

The [English version of the Revit 2023 Developer's Guide](https://help.autodesk.com/view/RVT/2023/ENU/?guid=Revit_API_Revit_API_Developers_Guide_html) is
now online.

The development team is still trying to fix an issue with the Japanese text.

####<a name="3"></a> Forge Data Days

Finally, after the world-wide pandemic break, which also affected our traditional yearly DevDays, we can meet again live, face to face:

The Forge Data Days are coming up soon, a one-day, in-person event happening in 20 cities worldwide, to learn how to fully unlock the value of your data with Forge.
There are a limited number of seats available for each event, so I encourage you to register as soon as possible once you have decided that this is of interest for you.
 
At Forge Data Days, you’ll hear directly from experts on how Forge is powering enterprise digital transformation.
See how we are making data more granular, standardized, and transparent.
This can help you connect your teams, processes, and workflows.
Learn how new Forge data capabilities and APIs can increase your productivity, automation, and profitability. 
 
With the following exclusive Early Bird registration links for the first five locations, you can choose between different dates and European cities to join us at:
 
- May 31st &ndash; [Munich, Germany](https://cvent.autodesk.com/event/c064e191-cced-4cf6-a0ff-56a92a3c2689/summary)
- June 2nd &ndash; [Gothenburg, Sweden](https://cvent.autodesk.com/event/994e1f82-52fc-41a2-9a64-efadde9e4273/summary)
- June 7th &ndash; [Birmingham, UK](https://cvent.autodesk.com/event/bedd310d-fa7d-4b02-99dd-2c4c5b40293d/summary)
- June 9th &ndash; [Milan, Italy](https://cvent.autodesk.com/event/5733cfc3-51cf-41fb-bacf-457ba6b1ae97/summary)
- June 14th &ndash; [Barcelona, Spain](https://cvent.autodesk.com/event/84021b3b-9286-4586-af2a-c6b1f2b5f301/summary)
- [All event locations](https://forge.autodesk.com/forge-data-days)

Registration opens to the public today, May 3rd, and spots will fill up fast, so don't wait too long making up your mind...

To learn more about the event, please check out
the [Forge Data Days global event series announcement](https://forge.autodesk.com/blog/announcing-forge-data-days-global-event-series) and 
the [Forge Data Days event page](https://forge.autodesk.com/forge-data-days).

<center>
<img src="img/2022_forge_data_days.png" alt="Forge Data Days" title="Forge Data Days" width="800"/> <!-- 1200 -->
</center>

####<a name="4"></a> Obtaining Closed Loops for Joined Element Parts

Returning to the Revit API,
Richard [RPThomas108](https://forums.autodesk.com/t5/user/viewprofilepage/user-id/1035859) Thomas shared another of his brilliant solutions and another important entry in the list of
the [often overlooked Revit API Util](https://thebuildingcoder.typepad.com/blog/about-the-author.html#5.52) in 
the [Revit API discussion forum](http://forums.autodesk.com/t5/revit-api-forum/bd-p/160) thread
on how to [get curves of a joined slab](https://forums.autodesk.com/t5/revit-api-forum/get-curves-of-slab-was-joined/td-p/11140489),
to obtain separate curve loops for the separate parts of an element that are generated by joining it with another element:

**Questikon:** I have a slab that is joined with a beam.
How can I get two contiguous curves as highlighted in this picture?

<center>
<img src="img/2022_forge_data_days.png" alt="Forge Data Days" title="Forge Data Days" width="800"/> <!-- 1200 -->
</center>

**Answer:** The easiest way to obtain the loops for that is to reverse the join order within a transaction that is rolled back so that the beam cuts the slab.
Currently, with slab cutting beam, you will get a single edge loop for the slab top face with extra 'contextual' edges where the edge is hidden by the joins.

The below code uses the following `JoinGeometryUtils` API calls:

- GetJoinedElements
- IsCuttingElementInJoin
- SwitchJoinOrder

<pre class="code">
  Public Function Obj_220503a(commandData As ExternalCommandData, ByRef message As String, elements As ElementSet) As Result
    Dim IntUIApp As UIApplication = commandData.Application
    Dim IntUIDoc As UIDocument = commandData.Application.ActiveUIDocument
    Dim IntDoc As Document = IntUIDoc.Document

    Dim FEC_Flr As New FilteredElementCollector(IntDoc, IntDoc.ActiveView.Id)
    Dim ECF_Flr As New ElementClassFilter(GetType(Floor))

    Dim Els As List(Of Element) = FEC_Flr.WherePasses(ECF_Flr).ToElements
    Dim Curves As New List(Of Tuple(Of List(Of Curve), Plane))


    Using Tx As New Transaction(IntDoc, "Gather")
      If Tx.Start = TransactionStatus.Started Then
        For i = 0 To Els.Count - 1
          Dim El As Element = Els(i)
          Dim Ids As List(Of ElementId) = JoinGeometryUtils.GetJoinedElements(IntDoc, El)

          Dim FEC_Fra As New FilteredElementCollector(IntDoc, Ids)
          Dim ECF_Fra As New ElementCategoryFilter(BuiltInCategory.OST_StructuralFraming)
          Dim Els0 As List(Of Element) = FEC_Fra.WherePasses(ECF_Fra).ToElements

          For i0 = 0 To Els0.Count - 1
            If JoinGeometryUtils.IsCuttingElementInJoin(IntDoc, El, Els0(i0)) Then
              JoinGeometryUtils.SwitchJoinOrder(IntDoc, El, Els0(i0))
            End If
          Next
          IntDoc.Regenerate()

          Dim geomEl As GeometryElement = El.Geometry(New Options With {.DetailLevel = ViewDetailLevel.Fine})
          For Each ob As GeometryObject In geomEl
            If GetType(Solid) Is ob.GetType Then
              Dim S As Solid = ob

              For ix = 0 To S.Faces.Size - 1
                Dim PF As PlanarFace = TryCast(S.Faces.Item(ix), PlanarFace)
                If PF Is Nothing Then Continue For Else
                If PF.FaceNormal.IsAlmostEqualTo(XYZ.BasisZ) Then
                  Dim CrvSet As New List(Of Curve)
                  Dim CLL As List(Of CurveLoop) = PF.GetEdgesAsCurveLoops
                  For Each CL As CurveLoop In CLL
                    For Each C As Curve In CL
                      CrvSet.Add(C)
                    Next
                  Next
                  Curves.Add(New Tuple(Of List(Of Curve), Plane)(CrvSet, PF.GetSurface))
                End If
              Next

            End If
          Next
        Next

        Tx.RollBack()
      End If
    End Using
    Using Tx As New Transaction(IntDoc, "Draw")
      If Tx.Start = TransactionStatus.Started Then

        For Each item As Tuple(Of List(Of Curve), Plane) In Curves
          Dim PL As Plane = item.Item2
          Dim SKP As SketchPlane = SketchPlane.Create(IntDoc, PL)

          For Each C As Curve In item.Item1
            IntDoc.Create.NewModelCurve(C, SKP)
          Next
        Next

        Tx.Commit()
      End If
    End Using

    Return Result.Succeeded
  End Function
</pre>

####<a name="5"></a> Create and Style Your QR Code

I was not aware how much freedom you can have in stylking a QR code until I took a look at
the [qrcode-monkey](https://www.qrcode-monkey.com).

####<a name="6"></a> La Serre &ndash; Greenhouse Wheelbarrow Ballet

Unrelated to Revit and other hi-tech, just for fun, if you feel like a five-minute humorous and rather poetic break, take a look at
[La Serre](https://youtu.be/G1XarNWgzCk) by Didier André and Jean-Paul Lefeuvre,
a greenhouse circus artist wheelbarrow ballet with banjo:

<iframe width="480" height="270" src="https://www.youtube.com/embed/G1XarNWgzCk" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

> Formés au Centre national des arts du cirque, Jean-Paul Lefeuvre et Didier André ... ces deux circassiens ont étayé leur univers jusqu'à créer en 2001 <i>La Serre</i>, spectacle poético-agricole ... Dans un univers ingénieux, ces "Buster Keaton" de l'horticulture parsèment d'humour absurde et de rêverie aérienne leur grande humanité.

> <i>Trained at the national centre of circus art, Jean-Paul Lefeuvre and Didier André ... created La Serre in 2001, a poetic-agricultural show ... in an ingenious universe, these "Buster Keatons" of horticulture sprinkle their great humanity with absurd humor and aerial reverie.</i>

