<p><head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<link rel="stylesheet" type="text/css" href="bc.css"></p>
<!-- https://highlightjs.org/#usage
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/styles/default.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/highlight.min.js"></script>
<script>hljs.highlightAll();</script>
-->

<!-- https://prismjs.com -->
<p><link href="https://cdn.jsdelivr.net/npm/prismjs@1.29.0/themes/prism.min.css" rel="stylesheet" /></p>
<script src="https://cdn.jsdelivr.net/npm/prismjs@1.29.0/components/prism-core.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/prismjs@1.29.0/plugins/autoloader/prism-autoloader.min.js"></script>
<style> code[class*=language-], pre[class*=language-] { font-size : 90%; } </style>

</style>
<p></head></p>
<!---

- Get BendRadius center of Cable Tray Fittings
  https://forums.autodesk.com/t5/revit-api-forum/get-bendradius-center-of-cable-tray-fittings/m-p/12757167

- mep tee identification and analysis
  Revit Tpiece geometric analysis
  https://forums.autodesk.com/t5/revit-api-forum/revit-tpiece-geometric-analysis/m-p/12995868

twitter:

 @AutodeskRevit #RevitAPI #BIM @DynamoBIM

&ndash; ...

linkedin:

#BIM #DynamoBIM #AutodeskAPS #Revit #API #IFC #SDK #Autodesk #AEC #adsk

the [Revit API discussion forum](http://forums.autodesk.com/t5/revit-api-forum/bd-p/160) thread

<center>
<img src="img/" alt="" title="" width="600"/>
<p style="font-size: 80%; font-style:italic"></p>
</center>

-->

<h3>Cable Tray Bend and Tee Analysis</h3>
<p>A quick dive into the geometric analysis of various MEP fittings:</p>
<ul>
<li><a href="#2">Cable tray bend radius</a></li>
<li><a href="#3">Tee branch identification</a></li>
</ul>
<h4><a name="2"></a> Cable Tray Bend Radius</h4>
<p><a href="https://fr.linkedin.com/in/pierre-navarra-62032a107">Pierre Navarra</a> of <a href="http://www.sona-architecture.com">Sona-Architecture</a>
solved how
to <a href="https://forums.autodesk.com/t5/revit-api-forum/get-bendradius-center-of-cable-tray-fittings/m-p/12757167">get <code>BendRadius</code> center of cable tray fittings</a>
with lots of valuable help from Moustafa Khalil from <a href="https://sharpbim.hashnode.dev/">SharpBIM coding</a> and Mohamed Arshad K:</p>
<p><strong>Question:</strong>
I need to get the length of a cable tray fitting.
I could get length between connector A and B but this is not a correct method.
I'd like to get length of an arc between passing by A and B with center of BendRadius...
But how to get the center with API?</p>
<p><center>
  <img src="img/cabletraybend01.png" alt="Cable tray bend radius" title="Cable tray bend radius" width="300"/> <!-- Pixel Height: 675 Pixel Width: 993 -->
  <br/>
  <img src="img/cabletraybend02.png" alt="Cable tray bend radius" title="Cable tray bend radius" width="300"/> <!-- Pixel Height: 675 Pixel Width: 993 -->
</center></p>
<p><strong>Answer:</strong>
This may be somewhat tricky due to the fact that every content creator is free to set up the elbow fitting family definition as she pleases. So, it is hard to know what parameters are available and what they might mean. My off-hand suggestion to approach this would be the following:</p>
<ul>
<li>Determine the two connector origins and orientations for C1 and C2</li>
<li>They will give you the two connection points P1 and P2, and the connection orientation vectors Z1 and Z2 pointing into the fitting at C1 and C2</li>
<li>From these four points and vectors, you can calculate an arc that implements a fillet between the two neighbouring conduit straight line segments</li>
</ul>
<p>That is the best approximation I can think of offhand. If you have the bend width, radius, straight line extensions at the two ends of the bend, and/or other additional data, you can improve the calculation taking those into account.</p>
<p><strong>Response:</strong>
Indeed, I think the idea would be to find the center of a circle from the two connectors. I'd need to get the vectors at these points and take the perpendicular to these vectors. Then I could find their intersection and draw an arc between the two connectors.
But how do I get the vectors? By using the Transform object and then BasisXYZ?</p>
<p><center>
<img src="img/cabletraybend03.png" alt="Cable tray bend radius" title="Cable tray bend radius" width="300"/> <!-- Pixel Height: 675 Pixel Width: 993 -->
</center></p>
<p><strong>Answer:</strong>
Yes, exactly.
In the <a href="https://www.revitapidocs.com/2024/cb6d725d-654a-f6f3-fed0-96cc618a42f1.htm"><code>Connector</code> <code>CoordinateSystem</code> property</a>,
the coordinate system origin is the location of the connector and the Z-axis is normal to the connector, and thus also to the fitting face hosting it, and thus also collinear with the neighbouring conduit location line.</p>
<p><strong>Response:</strong>
I found this <a href="https://voltadynabim.blogspot.com/2022/06/dynamo-python-courbe-d-raccord-en-arc.html">post from Cyril Poupin in Python</a> with the following code:</p>
<pre><code class="language-py">  pair_sys_origin = [[con.CoordinateSystem, con.Origin] for con in conSet]
  pta = pair_sys_origin[0][1].ToPoint()
  ptb = pair_sys_origin[1][1].ToPoint()
  vector = pair_sys_origin[0][0].BasisZ.Negate().ToVector()
  arc = DS.Arc.ByStartPointEndPointStartTangent(pta, ptb, vector)
  return arc, arc.Length</code></pre>

<p>I tried to translate it in C#, but the Dynamo API provides a function called <code>ByStartPointEndPointStartTangent</code>, and I must create my own .... mmm ... this is a geometric problem.</p>
<pre><code class="language-cs">// méthode à partir de deux connecteurs
if (connectors.Size == 2)
{
  // Transforme le Set en liste
  var castConnectors = connectors.Cast&lt;Connector&gt;();
  List&lt;Connector&gt; connectorList = castConnectors.ToList();
  // get first point
  Transform transformPtA = connectorList[0].CoordinateSystem;
  XYZ originPtA = transformPtA.Origin;

  // get Vector from this point
  XYZ vector = transformPtA.BasisZ.Negate();
  // get second point
  Transform transformPtB = connectorList[1].CoordinateSystem;
  XYZ originPtB = transformPtB.Origin;

  // Get arc from those points
  Arc arc = Arc.Create(originPtA, originPtB, vector);

  length = arc.Length;
}</code></pre>

<p><strong>Answer:</strong>
I think there is no direct way to get it.
You need to identify the two connectors for which you want to determine the outer radius.
From these 2 connectors, extract the origin points.
These points are crucial for finding the center point of the arc.
Getting the center point can be achieved by drawing a perpendicular line to the cable tray curve direction and projecting the second point onto this line, by which we can locate the center.
Next, draw an arc connecting the two points with the radius.
The radius can be measured by getting the distance between any of the connectors to the center point we evaluated.
This approach will establish the centerline connection between the two MEP curves.
Finally, by using the <code>CreateOffset</code> function with a distance equal to half the cable tray width, we can achieve our desired outcome.</p>
<p>Below is sample code that summarizes the process; you need to take care of the angles needed to draw the arc.
The start angle has to be less than the end angle.
Another thing I noticed in most of MEP Fittings, especially the elbow kind, the path that is used to sweep the profile, is composed of two lines and one arc.
The two lines give a smooth connection when used.
So, you need also to take care of such things in order to get an accurate result.</p>
<p>I wrote the sample below for the 90 degrees case.
I think in the other angle cases, you need to take care of the projection of the second point.
Probably, you need to create another perpendicular line and find the intersection between the two lines.</p>
<pre><code class="language-cs">// assuming you already have the two connectors.
// we get the curves lines from its owner.
var horizontalLine = ((LocationCurve)connectorA.Owner.Location).Curve as Line;
var verticalLine = ((LocationCurve)connectorB.Owner.Location).Curve as Line;

// catch the distance and location of the 2 connectors and the distance between
var originA = connectorA.Origin;
var originB = connectorB.Origin;
var diagonalDistance = originA.DistanceTo(originB);

// get the sketchplan used to draw such cable trays
var sketchPlan = SketchPlane.Create(Doc, ((MEPCurve)connectorA.Owner).ReferenceLevel.Id).GetPlane();

// now we need draw a perpendicular line to any of the mep curves.
var perDirection = horizontalLine.Direction.CrossProduct(sketchPlan.Normal);
var perpL1 = Line.CreateBound(originA - perDirection * diagonalDistance, originA + perDirection * diagonalDistance);

// then project the second point over this perpendicular curve to get the center point
var centerPoint = perpL1.Project(originB).XYZPoint;

// arc requires 2 angles start and end
double angleX = sketchPlan.XVec.AngleTo((originA - centerPoint).Normalize());
double angleY = sketchPlan.XVec.AngleTo((originB - centerPoint).Normalize());

// draw the arc <= this is in the zero position "sketchplan origin point"
Curve arc = Arc.Create(sketchPlan, originB.DistanceTo(centerPoint), angleX, angleY);

// move the arc to the center point
arc = arc.CreateTransformed(Transform.CreateTranslation(centerPoint));

// create the offset needed to get the outer Radius
arc = arc.CreateOffset(((MEPCurve)connectorA.Owner).Width / 2, sketchPlan.Normal);
</code></pre>

<p>Pipe elbow fittings often have a straight segment on each side before the arc begins, for connecting them to the neighbour parts.
Do the conduit elbows always connect immediately to the arc, with no straight segment before and after?</p>
<p><strong>Response:</strong>
I determined the center of my arc.
However, I'm stuck on creating the arc.
My bend doesn't always go in the right direction and it doesn't go between my two connector points...</p>
<pre><code class="language-cs">//Transforme le Set en liste
var castConnectors = connectors.Cast&lt;Connector&gt;();
List&lt;Connector&gt; connectorList = castConnectors.ToList();

Connector connectorA = connectorList[0];
Connector connectorB = connectorList[1];

#region connectorA_Perpendicular
//get Transform
Transform transformPtA = connectorA.CoordinateSystem;
//get origin
XYZ originPtA = transformPtA.Origin;
//get direction
XYZ directionA = (connectorA.Owner.Location as LocationPoint).Point;
//set line between origin and direction of owner
Line lineA = Line.CreateBound(originPtA, directionA);

//get perpendicular
XYZ normalA = lineA.Direction.Normalize();
XYZ dirA = new XYZ(0, 0, 1);
XYZ crossA = normalA.CrossProduct(dirA);
XYZ endA = originPtA + crossA.Multiply(4);
XYZ endAMirror = originPtA + crossA.Multiply(-4);
Line linePerpendicularA = Line.CreateBound(endA, endAMirror);

#endregion

#region connectorB_Perpendicular
//get Transform
Transform transformPtB = connectorB.CoordinateSystem;
//get origin
XYZ originPtB = transformPtB.Origin;
//get direction
XYZ directionB = (connectorB.Owner.Location as LocationPoint).Point;
//set line between origin and direction of owner
Line lineB = Line.CreateBound(originPtB, directionB);

//get perpendicular
XYZ normalB = lineB.Direction.Normalize();
XYZ dirB = new XYZ(0, 0, 1);
XYZ crossB = normalB.CrossProduct(dirB);
XYZ endB = originPtB + crossB.Multiply(4);
XYZ endBMirror = originPtB + crossB.Multiply(-4);
Line linePerpendicularB = Line.CreateBound(endB, endBMirror);

#endregion

//get intersection between perpendiculars
XYZ centerOfArc = null;
IntersectionResultArray intersectionResults = new IntersectionResultArray();
SetComparisonResult setCR = linePerpendicularA.Intersect(linePerpendicularB, out intersectionResults);

if (setCR == SetComparisonResult.Overlap)
{
    if (intersectionResults != null && intersectionResults.Size == 1)
    {
        //there is one point interesction
        IntersectionResult iResult = intersectionResults.get_Item(0);
        centerOfArc = iResult.XYZPoint;
        _geometries.Add(Point.Create(centerOfArc));
    }
}

if (centerOfArc != null)
{
    //Set arc from point A and B
    double radius = centerOfArc.DistanceTo(originPtA);

    XYZ xAxis = new XYZ(1, 0, 0);   // The x axis to define the arc plane. Must be normalized
    XYZ yAxis = new XYZ(0, 1, 0);   // The y axis to define the arc plane. Must be normalized
    Arc arc = Arc.Create(centerOfArc, radius, 0, Math.PI / 2.0, xAxis, yAxis);
    _geometries.Add(arc);
}</code></pre>

<p><center>
<img src="img/cabletraybend04.png" alt="Cable tray bend radius" title="Cable tray bend radius" width="300"/> <!-- Pixel Height: 675 Pixel Width: 993 -->
</center></p>
<p>And what about Cable Tray Fittings which are vertical or visible in section like this?</p>
<p><center>
<img src="img/cabletraybend05.png" alt="Cable tray bend radius" title="Cable tray bend radius" width="300"/> <!-- Pixel Height: 675 Pixel Width: 993 -->
</center></p>
<p><strong>Answer:</strong>
I found a new approach to get the center curve of the duct and use the Revit API library to create an Arc to represent it:</p>
<pre><code class="language-cs">  ElementId id = uidoc.Selection.PickObject(
    Autodesk.Revit.UI.Selection.ObjectType.Element).ElementId;

  FamilyInstance inst = doc.GetElement(id) as FamilyInstance;

  Options opt = new Options();
  opt.ComputeReferences = true;
  opt.DetailLevel = ViewDetailLevel.Coarse;

  GeometryElement geoElement = inst.get_Geometry(opt);

  using (Transaction createArc = new Transaction(doc, "Create Arc"))
  {
    createArc.Start();

    foreach (GeometryInstance geoInst in geoElement)
    {
      if(geoInst != null)
      {
        foreach (GeometryObject obj in geoInst.GetInstanceGeometry())
        {
          if (obj is Arc)
          {
            doc.Create.NewModelCurve(obj as Curve,
              SketchPlane.Create(
                doc,
                Plane.CreateByNormalAndOrigin((obj as Arc).Normal,
                (obj as Arc).GetEndPoint(0))));
          }
        }
      }
    }
    createArc.Commit();
  }</code></pre>

<p><center>
<img src="img/cabletraybend06.gif" alt="Cable tray bend radius" title="Cable tray bend radius" width="300"/> <!-- Pixel Height: 675 Pixel Width: 993 -->
</center></p>
<p><strong>Response:</strong>
YouHou!!! It works!!
So yes, depending on the level of view detail, the instances returned by <code>GetInstanceGeometry</code> are not the same.
Secret is changing the <code>ViewDetailLevel</code> to <code>Coarse</code>!
The good surprise is that <code>Arc</code> and <code>Line</code> have an <code>ApproximateLength</code> property, so I don't have to run a transaction.</p>
<p><center>
<img src="img/cabletraybend07.png" alt="Cable tray bend radius" title="Cable tray bend radius" width="300"/> <!-- Pixel Height: 675 Pixel Width: 993 -->
<br/>
<img src="img/cabletraybend08.png" alt="Cable tray bend radius" title="Cable tray bend radius" width="300"/> <!-- Pixel Height: 675 Pixel Width: 993 -->
<br/>
<img src="img/cabletraybend09.png" alt="Cable tray bend radius" title="Cable tray bend radius" width="300"/> <!-- Pixel Height: 675 Pixel Width: 993 -->
</center></p>
<p>The code looks like this:</p>
<pre><code class="language-cs">  Options opt = new Options();
  opt.ComputeReferences = true;
  opt.DetailLevel = ViewDetailLevel.Coarse;

  foreach (ElementId elemId in _uidoc.Selection.GetElementIds())
  {
    // normalement, un seul
    Element element = _uidoc.Document.GetElement(elemId);

    if (element.GetType() == typeof(FamilyInstance))
    {
      double approximateLength = 0;
      FamilyInstance famInst = element as FamilyInstance;

      GeometryElement geoElement = famInst.get_Geometry(opt);

      foreach (GeometryInstance geoInst in geoElement)
      {
        if (geoInst != null)
        {
          foreach(GeometryObject geoObj in geoInst.GetInstanceGeometry())
          {
            if (geoObj is Arc)
            {
              Arc arc = geoObj as Arc;
              approximateLength += arc.ApproximateLength;
            }
            if (geoObj is Line)
            {
              Line line = geoObj as Line;
              approximateLength += line.ApproximateLength;
            }
          }
        }
      }
      TaskDialog.Show("Message from dev",
        "Approximate length of instance is "
        + UnitUtils.ConvertFromInternalUnits(
          approximateLength,
          UnitTypeId.Centimeters));

    }
  }</code></pre>

<p>Thanks to all for your help, and to Mariyan for his <a href="https://youtu.be/FrFSPTRO9wY">tutos about vectors</a>!</p>
<h4><a name="3"></a> MEP Tee Branch Identification</h4>
<p>Andrej Licanin of <a href="https://bimexperts.com/">bimexperts</a> brought up a question and shared his MEP tee fitting identification and analysis solution in
the <a href="http://forums.autodesk.com/t5/revit-api-forum/bd-p/160">Revit API discussion forum</a> thread
on <a href="https://forums.autodesk.com/t5/revit-api-forum/revit-tpiece-geometric-analysis/m-p/12995868">Revit Tpiece geometric analysis</a>:</p>
<p><strong>Question:</strong>
I'm trying to make a function that will read a t-piece and return a coefficient based on a table from DIN 1988-300:</p>
<p><center>
  <img src="img/tee_identification_1.png" alt="Tee identification" title="Tee identification" width="750"/> <!-- Pixel Height: 675 Pixel Width: 993 -->
</center></p>
<p>I get T pieces by collecting family instances and checking their part type in the <code>MEPModel</code> field.
After that, I retrieve their connectors and obtain the flow values, but I can't determine the coefficients based on just that.
I would need some way to identify which connector is going straight and which one is branching off.
I thought the angle property could help me here, but no luck &ndash; in the families I'm looking at, they are all 0.
Any idea how to tackle this problem?
How could I determine which connector is coming from the side of a t piece?</p>
<p><strong>Answer:</strong>
You can look at the <a href="https://www.revitapidocs.com/2024/cb6d725d-654a-f6f3-fed0-96cc618a42f1.htm">connector coordinate system</a>.
Its Z axis points in the connector direction, so you can use that to determine the relative connector angles.</p>
<p><strong>Response:</strong>
Thanks Jeremy, it works:</p>
<p><center>
  <img src="img/tee_identification_2.png" alt="Tee identification" title="Tee identification" width="750"/> <!-- Pixel Height: 544 Pixel Width: 1,500 -->
</center></p>
<p>Here is the code for the function:</p>
<pre><code class="language-cs">  public static Element AnalyzeTee2(
    Element element,
    Document doc)
  {
    Element elementAtAngle = null;

    // Check if the element is a FamilyInstance

    if (!PipeNetworkSplitter.isSplitter(element))
    {
      return null;
    }

    List&lt;Connector&gt; tpieceConnectors = getConnectors(element);

    Connector connector1 = tpieceConnectors[0];
    Connector connector2 = tpieceConnectors[1];
    Connector connector3 = tpieceConnectors[2];

    XYZ zVector1 = connector1.CoordinateSystem.BasisZ;
    XYZ zVector2 = connector2.CoordinateSystem.BasisZ;
    XYZ zVector3 = connector3.CoordinateSystem.BasisZ;

    if (AreVectorsParallel(zVector1,zVector2))
      elementAtAngle = getConnectingConnector(connector3).Owner;
    if (AreVectorsParallel(zVector2,zVector3))
      elementAtAngle = getConnectingConnector(connector1).Owner;
    if (AreVectorsParallel(zVector1,zVector3))
      elementAtAngle = getConnectingConnector(connector2).Owner;

    return elementAtAngle;
  }

  public static bool AreVectorsParallel(
    XYZ vector1,
    XYZ vector2,
    double tolerance = 1e-6)
  {
    // Compute the cross product of the two vectors
    XYZ crossProduct = vector1.CrossProduct(vector2);

    // Check if the cross product is close
    // to zero vector within the given tolerance
    return crossProduct.IsAlmostEqualTo(XYZ.Zero, tolerance);
  }</code></pre>

<p>Many thanks to Andrej for sharing this solution.</p>